# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'AuthCoreAdapter', '1.4.0'
pod 'ParticleAuthCore', '1.4.0'
pod 'ParticleMPCCore', '1.4.0'
pod 'Thresh', '1.4.0'

pod 'ConnectCommon', '0.2.19'
pod 'ParticleNetworkBase', '1.4.0'

# from 1.14.0 you need add these two lines.
pod 'SwiftyUserDefaults', :git => 'https://github.com/SunZhiC/SwiftyUserDefaults.git', :branch => 'master'
pod 'SkeletonView', :git => 'https://github.com/SunZhiC/SkeletonView.git', :branch => 'main'

# help create transaction
pod 'ParticleWalletAPI', '1.4.0'
pod 'ProgressHUD', '13.8.6'
end

post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "x86_64"

      config.build_settings["ARCHS[sdk=iphoneos*]"] = "arm64"
    end
  
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
    config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end

    installer.generated_projects.each do |project|
      project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
           end
      end
    end
    
    # This is necessary for Xcode 14, because it signs resource bundles by default
    # when building for devices.
    installer.target_installation_results.pod_target_installation_results
    .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  
end
