# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'AuthCoreAdapter', '0.1.4'
pod 'ParticleAuthCore', '0.1.4'
pod 'ParticleMPCCore', '0.1.4'
pod 'Thresh', '0.1.4'


# helper create transaction
pod 'ParticleWalletAPI'

end

post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "x86_64"

      config.build_settings["ARCHS[sdk=iphoneos*]"] = "arm64"
    end
  
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
    config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end

    installer.generated_projects.each do |project|
      project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
           end
      end
    end
  
end
